"""Initial migration.

Revision ID: a19c71d70fa4
Revises: 
Create Date: 2025-09-16 00:33:22.019605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19c71d70fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'active_session',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_email', sa.String(length=32), nullable=False),
        sa.Column('session_token', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('log_id', sa.String(length=64), nullable=False),
        sa.Column('user_email', sa.String(length=32), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=True),
        sa.Column('action', sa.String(length=16), nullable=False),
        sa.Column('module', sa.String(length=512), nullable=True),
        sa.Column('submodule', sa.String(length=512), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=True),
        sa.Column('previous_data', sa.Text(), nullable=True),
        sa.Column('new_data', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('ip_address2', sa.String(length=45), nullable=True),
        sa.Column('ip_address3', sa.String(length=45), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('device_info', sa.JSON(), nullable=True),
        sa.Column('affected_records', sa.Text(), nullable=True),
        sa.Column('change_reason', sa.Text(), nullable=True),
        sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('log_creation_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('login_type', sa.String(length=16), nullable=True),
        sa.Column('error_codes', sa.String(length=16), nullable=True),
        sa.Column('authorization_check', sa.Boolean(), nullable=True),
        sa.Column('application_version', sa.String(length=16), nullable=True),
        sa.Column('api_endpoints', sa.Text(), nullable=True),
        sa.Column('database_involved', sa.String(length=255), nullable=True),
        sa.Column('job_id', sa.String(length=64), nullable=True),
        sa.Column('job_judged_by', sa.String(length=32), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=512), nullable=False),
        sa.Column('module', sa.String(length=512), nullable=False),
        sa.Column('permission_type', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('registered_on', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_logout', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_session', sa.String(length=255), nullable=True),
        sa.Column('last_login_type', sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'jobs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_id', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=False),
        sa.Column('module', sa.String(length=512), nullable=False),
        sa.Column('job_data_id', sa.String(length=64), nullable=True),
        sa.Column('submodule', sa.String(length=512), nullable=False),
        sa.Column('added_on', sa.DateTime(), nullable=False),
        sa.Column('executed_by', sa.String(length=64), nullable=True),
        sa.Column('executed_on', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('progress', sa.Integer(), nullable=False),
        sa.Column('input', sa.Text(), nullable=True),
        sa.Column('output', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['email'], ['users.email'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_data_id'),
        sa.UniqueConstraint('job_id')
    )
    op.create_table(
        'jobHistory',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('job_id', sa.String(length=64), nullable=False),
        sa.Column('action', sa.String(length=255), nullable=True),
        sa.Column('status_from', sa.String(length=16), nullable=False),
        sa.Column('status_to', sa.String(length=16), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobHistory')
    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('audit_logs')
    op.drop_table('active_session')
    # ### end Alembic commands ###
